### ISSUE TITLE
Build fails with libSSL 1.1

### ISSUE THREAD

**Issue by Spike29** [mbasaglia/Melanobot_v2#74]
Hello,

I tried to build Melanobot on Debian 9 with OpenSSL 1.1, but build fails with this error: 
[melanobot_compile_error.txt](https://github.com/mbasaglia/Melanobot_v2/files/1194402/melanobot_compile_error.txt)

Hopefully, libSSL1.0.0 and libSSL1.0.2 are on Debian 9 repositories, and Melanobot builds fine with these versions.

**Comment by surkeh** [comment]
There was an interface change in 1.1.

void HMAC_CTX_init(HMAC_CTX *ctx);
was changed to 
HMAC_CTX *HMAC_CTX_new(void);

Simple changes required in Melanobat_v2/modules/xonotic/encryption.cpp.  1.0.2 has serious known vulnerabilites so I will make a pull request if I can figure out an unrelated issue with std::variant.

https://www.openssl.org/docs/man1.0.2/crypto/HMAC.html
https://www.openssl.org/docs/man1.1.0/crypto/HMAC.html

**Comment by surkeh** [comment]
@mbasaglia, appreciate all your work on this project.  Thanks for getting that in.
