### ISSUE TITLE
Report which server is refusing connection

### ISSUE THREAD

**Issue by MarioSMB** [mbasaglia/Melanobot_v2#77]
The current message "Connection refused" is very unclear when your bot is connected to 10-20 servers, it would be nice if such errors could mention *which* server is having trouble.

**Comment by mbasaglia** [comment]
I've made network errors more verbose, now it shows the connection name (as from the config file) and the ip:port)

eg:
`[2018-02-07 14:39:24]xon     !Network Error: Connection refused (xon_localhost localhost:26000)`
